# Generated by Django 2.0.3 on 2018-03-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField()),
                ('venue', models.CharField(max_length=50)),
                ('startDate', models.DateTimeField()),
            ],
            options={
                'ordering': ['startDate'],
            },
        ),
    ]
