# Generated by Django 2.0.3 on 2018-04-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
