# Generated by Django 2.0.3 on 2018-04-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_event_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='startDate',
            new_name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='dateText',
            field=models.CharField(default='2001', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='priceText',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='sourceLink',
            field=models.CharField(default='eventnear.us', max_length=250),
        ),
    ]
